$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$InputHtml = Join-Path $Root "index.html"
$OutputHtml = Join-Path $Root "mobile.html"

function Read-Utf8File($Path) {
    return Get-Content -Path $Path -Raw -Encoding UTF8
}

function Get-RelativeFilePath($Reference) {
    $clean = [System.Net.WebUtility]::HtmlDecode($Reference.Trim())

    if ($clean -match '^(?i)(https?:|data:|mailto:|tel:|#|//)') {
        return $null
    }

    $withoutQuery = ($clean -split '[?#]', 2)[0]
    if ([string]::IsNullOrWhiteSpace($withoutQuery)) {
        return $null
    }

    $candidate = Join-Path $Root ($withoutQuery -replace '/', [System.IO.Path]::DirectorySeparatorChar)
    if (Test-Path -Path $candidate -PathType Leaf) {
        return (Resolve-Path $candidate).Path
    }

    return $null
}

function Get-MimeType($Path) {
    switch ([System.IO.Path]::GetExtension($Path).ToLowerInvariant()) {
        ".avif" { "image/avif"; break }
        ".bmp" { "image/bmp"; break }
        ".gif" { "image/gif"; break }
        ".jpg" { "image/jpeg"; break }
        ".jpeg" { "image/jpeg"; break }
        ".png" { "image/png"; break }
        ".svg" { "image/svg+xml"; break }
        ".webp" { "image/webp"; break }
        ".ico" { "image/x-icon"; break }
        ".woff" { "font/woff"; break }
        ".woff2" { "font/woff2"; break }
        default { "application/octet-stream" }
    }
}

function Convert-ToDataUri($Path) {
    $bytes = [System.IO.File]::ReadAllBytes($Path)
    $base64 = [Convert]::ToBase64String($bytes)
    return "data:$(Get-MimeType $Path);base64,$base64"
}

function Convert-CssUrls($Css) {
    return [regex]::Replace($Css, 'url\(([''"" ]?)([^\)''""]+)([''"" ]?)\)', {
        param($match)

        $reference = $match.Groups[2].Value.Trim()
        $path = Get-RelativeFilePath $reference
        if ($null -eq $path) {
            return $match.Value
        }

        return "url('$(Convert-ToDataUri $path)')"
    })
}

function Convert-ImageSources($Html) {
    return [regex]::Replace($Html, '(<(?:img|source)\b[^>]*?\bsrc=)([""''])([^""'']+)(\2)', {
        param($match)

        $path = Get-RelativeFilePath $match.Groups[3].Value
        if ($null -eq $path) {
            return $match.Value
        }

        return "$($match.Groups[1].Value)$($match.Groups[2].Value)$(Convert-ToDataUri $path)$($match.Groups[4].Value)"
    }, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
}

function Inline-Stylesheets($Html) {
    return [regex]::Replace($Html, '<link\s+([^>]*?rel=[""'']stylesheet[""''][^>]*?href=[""'']([^""'']+)[""''][^>]*)>', {
        param($match)

        $path = Get-RelativeFilePath $match.Groups[2].Value
        if ($null -eq $path) {
            return $match.Value
        }

        $css = Convert-CssUrls (Read-Utf8File $path)
        return "<style>`n$css`n</style>"
    }, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
}

function Inline-Scripts($Html) {
    return [regex]::Replace($Html, '<script\s+[^>]*?src=[""'']([^""'']+)[""''][^>]*>\s*</script>', {
        param($match)

        $path = Get-RelativeFilePath $match.Groups[1].Value
        if ($null -eq $path) {
            return $match.Value
        }

        $js = (Read-Utf8File $path) -replace '</script>', '<\/script>'
        return "<script>`n$js`n</script>"
    }, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
}

$html = Read-Utf8File $InputHtml
$html = Inline-Stylesheets $html
$html = Inline-Scripts $html
$html = Convert-ImageSources $html

$marker = "<!-- Generated by scripts/build-mobile.ps1. Do not edit mobile.html directly. -->"
$html = $html -replace '<!doctype html>', "<!doctype html>`n$marker"

Set-Content -Path $OutputHtml -Encoding UTF8 -Value $html
Write-Host "Generated $OutputHtml"
